apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: 44%G&Orx60HJ
  PGDATA: /var/lib/postgresql/data/pgdata
