apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-bpilot
  labels:
    app: odoo-bpilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-helm
  template:
    metadata:
      labels:
        app: first-helm
    spec:
      containers:
      - name: first-helm
        image: nginx
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort: 8069
        envFrom:
            - configMapRef:
                name: db-config

