apiVersion: v1
kind: Service
metadata:
  name: first-helm-service
spec:
  type: NodePort
  selector:
    app: first-helm
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30300
